### ISSUE TITLE
저장소 이동

### ISSUE THREAD

**Issue by xoxwgys56** [news-reply-sentiment-analysis/frontend#1]
@waltererz 님.  

여쭤보지 않고, 저장소를 그룹으로 이동해서 죄송합니다.  
이렇게 옮기면 관리하기 편할 것 같아서 organization으로 만들었는데요. 괜찮으실까요?

옮기 다음에 여쭤보는게 이상하긴 하네요..

**Comment by waltererz** [comment]
저는 상관없습니다 ㅎㅎ 팀을 만들 수도 있군요

**Comment by xoxwgys56** [comment]
@waltererz 

기존에 `waltererz` 계정으로 만드신 저장소와 현재 이 저장소는 연동되어 있지 않습니다.  
제 경우, `settings` -> `options` -> `transfer`로 이 저장소로 옮겼습니다.  

기존 저장소를 유지하셔도 되고, 없애셔도 될 것 같습니다.  
무언가를 적용하시거나 변경하셔야 되는 것은 아니고, 알고 계시겠지만 확인해두시면 좋을 것 같아 말씀드립니다.
